name: Rclone sync
on:
  schedule: 
    - cron: '0 12 * * 1'
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
            
      - run: 'rclone sync main_viethoangprobie: backup_sinhvien:'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:

          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Backup results
          to: hoangprobie250106@gmail.com,phamviethoang206@gmail.com
          from: Pham Viet Hoang
          body: Build job of ${{github.repository}} completed succesfully!